config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  
  resources :users do
    resources :friends
  end
  resources :tweets do
    resources :likes
    resources :retweet
  end
  get 'api/news'
  get 'api/:fecha1/:fecha2', to: 'api#between_dates'
  post 'api/create_tweet', to: 'api#create_tweet'
  post '/tweets_search', to: 'tweets#search'
  post '/tweets/:id', to: 'tweets#create_retweet'
  root 'tweets#index'
end

app/models/tweet.rb
# == Schema Information
#
# Table name: tweets
#
#  id         :integer          not null, primary key
#  text       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
# Indexes
#
#  index_tweets_on_user_id  (user_id)
#
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :retweets, dependent: :destroy
  has_many :likes, dependent: :destroy

  scope :tweets_for_me, ->(friends) { where(user: friends).order(id: :desc) }

  validates_presence_of :text, on: :create, message: "can't be blank"

  def liked_by?(liking_user)
    likes.any? { |l| l.user == liking_user }
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :search]

  def index
    @tweet = Tweet.new
    @tweets = if user_signed_in? && !params.has_key?(:search)
                Tweet.includes(:likes, :retweets).tweets_for_me(current_user_friends).page params[:page]
              else
                Tweet.includes(:likes, :retweets).order(id: :desc).page params[:page]
              end

    @tweets = @tweets.where("text LIKE '%#{params[:search]}%' ") if params.has_key? :search
  end

  def show
    @tweet = Tweet.find(params.require(:id))
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new tweet_create_params
    if @tweet.save
      redirect_to root_path
    else
      render root_path
    end
  end

  def destroy
  end

  def search
    redirect_to action: :index, search: params[:search]
  end

  def create_retweet
    @tweet = Tweet.find(params.require(:id))
    @retweet = @tweet.retweets.new(user: current_user)
    if @retweet.save
      redirect_to root_path
    else
      render root_path
    end
  end

  private

  def tweet_create_params
    params.require(:tweet).permit(:text).merge(user: current_user)
  end

  def current_user_friends
    @current_user_friends = current_user.friends.joins(:friend).map(&:friend) << current_user
  end
end

app/helpers/tweet_helper.rb
module TweetHelper
    def render_with_hashtags(content)
        content_words = content.split(" ")
        content_with_links = content_words.map do |word| 
        if word.include?("#")
            link_to word, tweets_path(search: word)
        else
            word
        end
    end
    
        content_with_links.join(" ")
    end
end

app/views/tweets/_form.html.erb
<%= form_with model: @tweet, class: "nifty_form" do |f| %>
<% if @tweet.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@tweet.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @tweet.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="form-group">
<%= f.label "new tweet" , class: "d-block"%>
<%= f.text_area :text, size: "60x5", class:"form-control" %>
</div>
  <%= f.submit "Create", class:"btn btn-primary" %>
<% end %>

app/views/tweets/destroy.html.erb
<h1>Tweet#destroy</h1>
<p>Find me in app/views/tweet/destroy.html.erb</p>

app/views/tweets/index.html.erb
<% if user_signed_in? %>
  <%= render partial: "form" %>
<% end %>

<% @tweets.each do |tweet| %>
  <div class="card my-3">
    <div class="card-body">
      <div class="media">
          <div class="container">
              <div class="row">
                  <div class=col-md-2>
                      <%= tweet.user.avatar.attached? ? image_tag(url_for(tweet.user.avatar), class: "img-thumbnail img-fluid rounded-circle thumbnail-photo") : image_tag(tweet.user.gravatar_url, class: "img-thumbnail img-fluid rounded-circle") %>
                      <%= link_to  "ver perfil", user_path(tweet.user), class: "btn btn-small btn-secondary" %>
                  </div>
                  <div class="media-body col-md-10">
                      <h5 class="mt-0"><%= tweet.user.email%> - hace <%= link_to(time_ago_in_words(tweet.created_at), tweet_path(tweet))%></h5>
                      <p><%= render_with_hashtags(tweet.text).html_safe %></p>
                      <%= link_to( tweet_likes_path(tweet), class:"btn btn-info btn-small") do%>
                        <%= tweet.likes.size %> <%= fa_icon("heart") %>
                      <%end%>
                      <%= button_to( tweet_path(tweet), class: "btn btn-info btn-small ml-5", form_class: "d-inline-block") do%>
                          <%= tweet.retweets.size %> <%= fa_icon("retweet") %>
                      <%end%>
                  </div>
              </div>
          </div>
      </div>
    </div>
  </div>
  <% end %>
<%= paginate @tweets %>

app/views/tweets/new.html.erb
<%= render "form" %>

app/views/tweets/show.html.erb
<div class="card my-3">
  <div class="card-body">
    <div class="media">
        <div class="container">
            <div class="row">
                <div class=col-md-2>
                    <%= @tweet.user.avatar.attached? ? image_tag(url_for(@tweet.user.avatar), class: "img-thumbnail img-fluid rounded-circle thumbnail-photo") : image_tag(@tweet.user.gravatar_url, class: "img-thumbnail img-fluid rounded-circle") %>
                    <%= @tweet.user.email%>
                </div>
                <div class="media-body col-md-10">
                    <h5 class="mt-0"><%= @tweet.id %> - hace <%= link_to(time_ago_in_words(@tweet.created_at), tweet_path(@tweet))%></h5>
                    <p><%= @tweet.text %></p>
                    <%= link_to( tweet_likes_path(@tweet), class:"btn btn-info btn-small") do%>
                      <%= @tweet.likes.size %> <%= fa_icon("heart") %>
                    <%end%>
                    <%= button_to( tweet_path(@tweet), class: "btn btn-info btn-small ml-5", form_class: "d-inline-block") do%>
                        <%= @tweet.retweets.size %> <%= fa_icon("retweet") %>
                    <%end%>
                </div>
            </div>
        </div>
    </div> 
  </div>
</div>

<h4>Likes:</h4>

<div class="container">
  <% @tweet.likes.each do |like| %>
    <%= like.user.avatar.attached? ? image_tag(url_for(like.user.avatar), class: "img-thumbnail img-fluid rounded-circle thumbnail-photo d-inline-block") : image_tag(like.user.gravatar_url, class: "img-thumbnail img-fluid rounded-circle mw-25") %>
  <% end %>
</div>