config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  
  resources :users do
    resources :friends
  end
  resources :tweets do
    resources :likes
    resources :retweet
  end
  get 'api/news'
  get 'api/:fecha1/:fecha2', to: 'api#between_dates'
  post 'api/create_tweet', to: 'api#create_tweet'
  post '/tweets_search', to: 'tweets#search'
  post '/tweets/:id', to: 'tweets#create_retweet'
  root 'tweets#index'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  authentication_token   :string(30)
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  username               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_authentication_token  (authentication_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  include Gravtastic
  gravtastic
  
  acts_as_token_authenticatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :tweets, dependent: :destroy
  has_many :friends, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :retweets, dependent: :destroy

  before_destroy :remove_friend_reference


  def remove_friend_reference
    Friend.where(friend_id: id).destroy_all
  end

  def friends?(user)
    user.friends.find_by(friend: id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params.require(:id))
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="card" style="width: 18rem;">
    <%= @user.avatar.attached? ? image_tag(url_for(@user.avatar), class: "img-thumbnail img-fluid") : image_tag(@user.gravatar_url, class: "img-thumbnail img-fluid") %>   
  <div class="card-body">
    <h5 class="card-title"><%= @user.email%></h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <% if @user.id != current_user.id %>
        <%= button_to( user_friends_path(@user), class: "btn btn-info btn-small ml-5", form_class: "d-inline-block") do%>
            <%= @user.friends?(current_user) ? "Unfollow" : "Follow" %>
        <%end%>
    <%end%>
  </div>
</div>